Issue 2.
greenpress/content-service pull request #15
Opened 2020-08-23 22:58 UTC by ShiraRotman

2020-08-24 10:17 UTC, davidmeirlevy requested changes

2020-08-24 10:17 UTC, davidmeirlevy commented on migrator/index.js
>    }
Why?

2020-08-24 10:17 UTC, davidmeirlevy commented on package.json
> +    "validator": "^13.1.1"
Not needed

2020-08-24 10:17 UTC, davidmeirlevy commented on server/controllers/posts.js
> +	if (req.post.comments) {
It’s not scalable to store comments inside post object

2020-08-24 10:17 UTC, davidmeirlevy commented on server/controllers/comments.js
> +	else return validator.escape(content);
Mongoose already validates

2020-08-24 10:17 UTC, davidmeirlevy commented on server/controllers/comments.js
> +	const comment = {
Comment should be a separate collection and model

2020-08-24 10:17 UTC, davidmeirlevy commented on server/middleware/auth-check.js
> +    return res.status(401).set('Content-Type', 'application/json').end(authErr);
It’s on purpose..  the “return” of the response object creates memory leaks in node.

2020-08-24 10:17 UTC, davidmeirlevy commented on server/middleware/populate-user.js
> +	return new Promise(function(resolve, reject) {
Why?

2020-08-24 10:17 UTC, davidmeirlevy commented on server/models/comment.js
> -  post: { type: Schema.Types.ObjectId, ref: 'Post', required: true, index: true },
Why?

2020-08-24 10:17 UTC, davidmeirlevy commented on server/models/post.js
> +  comments: [CommentSchema]
It’s not scalable.

2020-08-24 16:13 UTC, ShiraRotman commented on migrator/index.js
>    }
Because the config object will still be null, so we have to fill it after the migration config is created. It happened to me the first time I tried to run the service, and then it failed since the config object was referenced.

2020-08-24 16:15 UTC, ShiraRotman commented on package.json
> +    "validator": "^13.1.1"
I need the validator to escape the comments.

2020-08-24 16:18 UTC, ShiraRotman commented on server/controllers/posts.js
> +	if (req.post.comments) {
And that's why I put the TODO comment in the post model to separate them to pages in the future.

2020-08-24 16:24 UTC, ShiraRotman commented on server/controllers/comments.js
> +	const comment = {
This is a relational approach. Comments are part of posts, so should be stored with them in a document DB. As I said, we can separate them to pages for scalability. Look at that: https://www.mongodb.com/blog/post/building-with-patterns-the-bucket-pattern

2020-08-24 16:25 UTC, ShiraRotman commented on server/middleware/populate-user.js
> +	return new Promise(function(resolve, reject) {
Because the calling function expects a promise to be returned.

2020-08-24 16:26 UTC, ShiraRotman commented on server/models/comment.js
> -  post: { type: Schema.Types.ObjectId, ref: 'Post', required: true, index: true },
This is a relational approach, see my previous comments.

2020-08-27 19:23 UTC, ShiraRotman commented on server/middleware/auth-check.js
> +    return res.status(401).set('Content-Type', 'application/json').end(authErr);
Do you have a link to an article about that?

2020-08-28 07:24 UTC, davidmeirlevy commented on server/controllers/posts.js
> +	if (req.post.comments) {
It’s already separated. Why un-separate them and make a comment to re-separate in the future?

2020-08-28 07:30 UTC, davidmeirlevy commented on package.json
> +    "validator": "^13.1.1"
https://www.npmjs.com/package/escape-html

X4 more weekly downloads, and it has only one fast function..

2020-08-28 07:31 UTC, davidmeirlevy commented on server/middleware/populate-user.js
> +	return new Promise(function(resolve, reject) {
The the mongoose find returns a promise. So it’s already returns a promise.

2020-08-28 07:32 UTC, davidmeirlevy commented on server/middleware/auth-check.js
> +    return res.status(401).set('Content-Type', 'application/json').end(authErr);
No. I tested memory leaks and I found it out.

2020-08-28 07:33 UTC, davidmeirlevy commented on server/controllers/comments.js
> +	const comment = {
If you want to support unlimited comments for posts, including fast searches for posts - this cannot scale.
It will make the posts search slower.

2020-08-28 15:10 UTC, ShiraRotman commented on server/controllers/posts.js
> +	if (req.post.comments) {
Because the re-separation will be to pages, the comments will be grouped together in buckets. See the article I linked to.

2020-08-28 15:18 UTC, ShiraRotman commented on server/controllers/comments.js
> +	const comment = {
I'm afraid a "join" approach in a document DB will actually make it much slower. Today, when you retrieve a post, you have to access all its comments documents. Paging will limit this number. If you want, I can do it now, so you'll be able to see it.

2020-08-28 15:29 UTC, ShiraRotman commented on server/middleware/populate-user.js
> +	return new Promise(function(resolve, reject) {
The returned promise is used in the function it's called from, so it's not returned from it.

2020-09-08 19:59 UTC, ShiraRotman commented on server/controllers/comments.js
> +	const comment = {
David, you didn't answer me. Do you want me to do the separation of comments to pages (including matching queries to retrieve them), as described in the link I referred to?

2020-09-21 12:30 UTC, davidmeirlevy commented
I'm closing this PR because of the changes in the comments model.

2020-09-21 12:30 UTC, closed without merging