Content blocks
greenpress/content-service pull request #21
Opened 2020-09-30 18:51 UTC by itays123

This is the content blocks backend implementation

2020-09-30 19:23 UTC, davidmeirlevy requested changes

2020-09-30 19:23 UTC, davidmeirlevy commented on server/routes/blocks.js
> +    .get("/api/blocks", populateUser, getBlockList)
Guests and regular users doesn’t need to have access to get list of all blocks.

2020-09-30 19:23 UTC, davidmeirlevy commented on server/models/block.js
> +  if (useCache) {
Search blocks is a method that should be available to editors only from the admin panel.
No need to cache it.

2020-09-30 19:23 UTC, davidmeirlevy commented on server/controllers/blocks.js
> +function getBlockList(req, res) {
It should be getBlocksList.. “Blocks”.

2020-09-30 19:23 UTC, davidmeirlevy commented on server/controllers/blocks.js
> +  const isFrontTargeted = reqQuery.target === "front" ||
This function should not be available for front use.. only from admin.

2020-09-30 19:23 UTC, davidmeirlevy commented on server/controllers/blocks.js
> +        { message: err || "error while creating block, try again" },
Avoid to pass the actual error to the frontend. It’s a security risk.

2020-09-30 19:23 UTC, davidmeirlevy commented on server/controllers/blocks.js
> +        { message: err || "error while updating block, try again" },
Avoid to pass the actual error to the frontend. It’s a security risk.

2020-09-30 19:23 UTC, davidmeirlevy commented on server/controllers/blocks.js
> +        { message: err || "error while deleting block, try again" },
Avoid to pass the actual error to the frontend. It’s a security risk.

2020-09-30 19:23 UTC, davidmeirlevy commented on server/models/block.js
> +  const q = () =>
If no one use it, remove it.

2020-10-01 05:26 UTC, itays123 commented on server/controllers/blocks.js
> +  const isFrontTargeted = reqQuery.target === "front" ||
onlyEditor or onlyAdmin?

2020-10-01 06:18 UTC, davidmeirlevy commented on server/controllers/blocks.js
> +  const isFrontTargeted = reqQuery.target === "front" ||
editor, from admin-panel.

2020-10-01 07:28 UTC, itays123 commented on server/controllers/blocks.js
> +  const isFrontTargeted = reqQuery.target === "front" ||
Got it.

2020-10-01 14:59 UTC, davidmeirlevy approved these changes

2020-10-01 14:59 UTC, merged